AWSTemplateFormatVersion: 2010-09-09
Description: |
  This template creates an EC2 instance to run static web site with Python Flask
Parameters:
  
Resources: 
  HasanInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-04cb4ca688797756f
      InstanceType: t2.micro
      KeyName: secondkey
      SecurityGroups: 
        !Ref HasanInstanceSG
        
      Tags: 
       - Key: Name  
         Value: !Sub Hasan {AWS::StackName} 

      UserData: 
        Fn::Base64:
          !Sub |
          #!/bin/bash
          yum update -y
          yum install python3 -y
          pip3 install Flask

          

  HasanInstanceSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SHH  # Required
      GroupName: hasansecurityportfolio
      SecurityGroupIngress: 
        IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0
        IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
    
      Tags: 
        - Key: Name
          Value: HasanInstance
     

Outputs:
 WebsiteURL:
   Description: 001-Roman-Numerals-Converter Application URL
   Value: !Sub 
     - http://${PublicAddress}
      - PublicAddress: !GetAtt HasanInstance.PublicDnsName
   
  
   